name: Continuous Security Scanning with Trivy

permissions: write-all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        run: docker build -t flask-app:ci .

      - name: Run Trivy Securtiy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'flask-app:ci'
          #format: 'table'
          severity: "HIGH,CRITICAL"
          format: sarif # Usa il formato SARIF
          output: trivy-results.sarif # Salva l'output in un file
          exit-code: '0'
          ignore-unfixed: true


      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif' # Specifica il file SARIF da caricare

