name: Trivy Scan and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t myapp:latest .

    - name: Run Trivy Security Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: myapp:latest
        format: table
        exit-code: 1  # Fail on vulnerabilities
    
    - name: Push Docker Image to DockerHub
      run: |
        docker tag myapp:latest mydockerhubuser/myapp:latest
        docker push mydockerhubuser/myapp:latest
        
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Deploy to Cloud Run
      run: |
        gcloud auth configure-docker
        gcloud run deploy my-app --image gcr.io/$PROJECT_ID/myapp:latest --region us-central1 --platform managed
